version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""     
      MYSQL_DATABASE: anime      
      MYSQL_USER: root             
      MYSQL_PASSWORD: ""          
    ports:
      - "3306:3306"               
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_laravel_app
    depends_on:
      - mysql
    ports:
      - "8000:8000"              
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: anime         
      DB_USERNAME: root          
      DB_PASSWORD:               
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
